### ISSUE TITLE
Scandoubler bug

### ISSUE THREAD

**Issue by mapfde** [MiSTer-devel/Arduboy_MiSTer#6]
With the latest update, the core can utilize the scandoubler to use analogue output to a 30 kHz CRT. Thanks for adding that option.

When any effect (HQ, scanlines) is selected, the scandoubler works and 30kHz signal is generated. But when "scandoubler fx": "None" is selected, a 15kHz signal is generated.

I think this is a bug, as I would expect a 30kHz signal without any further effects.

**Comment by mapfde** [comment]
This is similar to the bug https://github.com/MiSTer-devel/Aquarius_MISTer/issues/2 which got fixed in the latest update.

**Comment by sorgelig** [comment]
i've just released the version with forced_scandoubler support.

**Comment by mapfde** [comment]
I made another update, now it works also with the "None" selection.
